#!/bin/bash
if [ -d /tmp/my_first_directory ]; then
    rm -r /tmp/my_first_directory
    echo "Directory '/tmp/my_first_directory' deleted."
else
    echo "Directory '/tmp/my_first_directory' does not exist."
fi

